// File generated by FlutterFire CLI.
// Contains Firebase configuration options for your app.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5QSYMpob1_itltzeOZO4WCGcHPoEyAZs',
    appId: '1:454531507359:web:e1136c3a277d3f9885aeaa',
    messagingSenderId: '454531507359',
    projectId: 'shophub-db0c8',
    authDomain: 'shophub-db0c8.firebaseapp.com',
    storageBucket: 'shophub-db0c8.firebasestorage.app',
    measurementId: 'G-N5K5NTHND5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5QSYMpob1_itltzeOZO4WCGcHPoEyAZs',
    appId: '1:454531507359:web:e1136c3a277d3f9885aeaa',
    messagingSenderId: '454531507359',
    projectId: 'shophub-db0c8',
    storageBucket: 'shophub-db0c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5QSYMpob1_itltzeOZO4WCGcHPoEyAZs',
    appId: '1:454531507359:web:e1136c3a277d3f9885aeaa',
    messagingSenderId: '454531507359',
    projectId: 'shophub-db0c8',
    storageBucket: 'shophub-db0c8.firebasestorage.app',
    iosClientId: 'YOUR_IOS_CLIENT_ID',
    iosBundleId: 'com.example.shophub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5QSYMpob1_itltzeOZO4WCGcHPoEyAZs',
    appId: '1:454531507359:web:e1136c3a277d3f9885aeaa',
    messagingSenderId: '454531507359',
    projectId: 'shophub-db0c8',
    storageBucket: 'shophub-db0c8.firebasestorage.app',
    iosClientId: 'YOUR_IOS_CLIENT_ID',
    iosBundleId: 'com.example.shophub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5QSYMpob1_itltzeOZO4WCGcHPoEyAZs',
    appId: '1:454531507359:web:e1136c3a277d3f9885aeaa',
    messagingSenderId: '454531507359',
    projectId: 'shophub-db0c8',
    storageBucket: 'shophub-db0c8.firebasestorage.app',
  );
}
